# Generated by Django 3.2.6 on 2021-08-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
    ]
