# Generated by Django 3.2.6 on 2021-08-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20210807_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
