# Generated by Django 3.2.6 on 2021-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_remove_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='street_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
