# Generated by Django 3.2.6 on 2021-08-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_auto_20210807_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
